library:
  source-dirs: src
tests:
  frpeng-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frpeng
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- random
- gloss
- Yampa
- base >= 4.7 && < 5
name: frpeng
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/frpeng
license: BSD3
executables:
  frpeng-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frpeng
description: Please see the README on GitHub at <https://github.com/githubuser/frpeng#readme>
